### ISSUE TITLE
Youtube audio

### ISSUE THREAD

**Issue by adrianrb** [soynerdito/BlueSound#11]
Hi!

Can redirect YT audio to my car stereo (it´s call profile only)?

Adrian

**Comment by soynerdito** [comment]
Short answer is Yes. It is suppose to redirect any audio from the device
regardless of the app (may be exceptions as I cannot test every app). The
application has no logic to restrict the kind of audio is redirected.

If it works on your device it will work with any audio. However this is
only mono sound. It's been a while I have used youtube with it. It used to
work. If not it is either a device specific or the Android version changed
something.
This app I did for myself and I use this app every day with sound from a
podcast app.
