### ISSUE TITLE
Was the LICENSE file removed on purpose?

### ISSUE THREAD

**Issue by ghost** [soynerdito/BlueSound#5]
Former versions included a LICENSE file stating it was public domain. Is this still true for the latest releae?

**Comment by soynerdito** [comment]
I migrated the code to android studio and for that moved all the files from
directory. Will be back. Sorry and thanks for pointing that. It is public
domain I do not want attribution or revenue from this. Free as in beer.

**Comment by soynerdito** [comment]
Just added the LICENSE, sorry for the inconvenience. Please if anyone want to use this code. Go ahead do. No need to attribute nothing. Code would be yours to do what you want. My purpose to this app is to be used and nothing more. I personally needed the app and din't wanted to use an app with adds for this silly task, so I made this. Figured out others might like it as well so here it is, nothing more.
Again, thanks for pointing it out.
